SAMPLE_TASK_NAMES = [
    'Design the solution',
    'Prepare for implementation',
    'Read the book',
    'Prepare the test/QA environment',
    'Install the product in the test/QA environment',
    'Buy eggs',
    'Implement distributed data feeds',
    'Implement a business system in the test/QA environment',
    'Schedule jobs',
    'Meet George',
    'Prepare the production environment.',
    'Install the product in the production environment.',
    'Pay bills',
    'Implement distributed data feeds in the production environment.',
    'Implement Source/390 data feeds in the production environment.',
    'Wash the dishes',
    'Implement a business system in the production environment.',
    'Install the history server.',
    'Install the Health Monitor.',
    'Create and present administrator and operator training information',
    'Create a solution maintenance plan',
    'Wash the car',
    'Buy a present for Sam\'s birthsday',
    'Walk the dog',
    'Call mom'
]
